# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MindExplorer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MindExplorer
  pod 'GoogleSignIn', '~> 4.4.0'


  target 'MindExplorerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MindExplorer-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MindExplorer-tvOS

  target 'MindExplorer-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
